### ISSUE TITLE
import module name

### ISSUE THREAD

**Issue by joreilly** [ge-org/multiplatform-swiftpackage#25]
I'm using following config (in https://github.com/joreilly/PeopleInSpace).... `PeopleInSpace` is being used for name of package but I still need to use `import common` in Swift code....I'm probably missing something obvious but is there way to change that name (or does gradle module name also need to change?)

```
multiplatformSwiftPackage {
    packageName("PeopleInSpace")
    swiftToolsVersion("5.3")
    targetPlatforms {
        iOS { v("13") }
    }
}
```

**Comment by ge-org** [comment]
Hi,

could be a bug, I need to look into it when I have some time.
For now, the easiest way to change the name of the framework is with the KMP configuration. In your `build.gradle.kts` file you have the following:

```kotlin
if (isiOSDevice) {
        iosArm64("iOS")
    } else {
        iosX64("iOS")
    }
```

To declare the framework name you can change it to this:

```kotlin
if (isiOSDevice) {
        iosArm64("iOS") {
          binaries.framework("PeopleInSpaceKit")
        }
    } else {
        iosX64("iOS") {
          binaries.framework("PeopleInSpaceKit")
        }
    }
```

**Comment by joreilly** [comment]
I had tried something like that and it hadn't worked but then re-read your README 

"Hint: If the cocoapods plugin is applied the name of the package will default to the value assigned to the frameworkName property. Otherwise, the value of the baseName property of the framework configuration will be used."

That's the case for this project.  Setting `frameworkName` in `cocoapods` seems to do the job.
