### ISSUE TITLE
Local created Swift Package cannot using locally

### ISSUE THREAD

**Issue by haitrvn** [ge-org/multiplatform-swiftpackage#52]
Hi everyone!
`multiplatformSwiftPackage {
    outputDirectory(File(projectDir,"presentationPackage"))
    packageName(project.name)
    swiftToolsVersion("5.3")
    targetPlatforms {
        iOS { v("13") }
    }
    distributionMode { local() }
}`

This is my config for create swift package, it's ok when using remote package(publish to github). But when i add to package manager from local file it not working, import in swift get "No such module <Package>" error

**Comment by orangetik1106** [comment]
Hi haitrvn, is there any alternative to use local spm for your case?

**Comment by haitrvn** [comment]
> Hi haitrvn, is there any alternative to use local spm for your case?

Sorry for the late response, it just doesn't work with local SPM import, so i use FAT iOS Framework instead
